# Informações de financiamento do projeto
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Descomente e configure os que você usar:

# github: matheuskindrazki
# patreon: username
# open_collective: clauderc
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ["https://example.com/sponsor"]
