name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is this related to a frustration?
      placeholder: I'm always frustrated when I have to manually...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: Add a new command `npx clauderc xyz` that...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area of clauderc does this relate to?
      options:
        - New Command
        - New Agent
        - New Skill
        - Stack Detection
        - Project Setup
        - Templates
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried using X but it doesn't work because...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used.
      placeholder: |
        ```bash
        # Example usage
        npx clauderc new-command --option
        ```

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in implementing this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
